const FILLER_TEXT = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

export default [{name: "Wings", awardNumber: 1,
  releaseYear: 1927,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Broadway Melody',
  awardNumber: 2,
  releaseYear: 1928,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'All Quiet On the Western Front',
  awardNumber: 3,
  releaseYear: 1930,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Cimarron',
  awardNumber: 4,
  releaseYear: 1931,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Grand Hotel',
  awardNumber: 5,
  releaseYear: 1932,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Cavalcade',
  awardNumber: 6,
  releaseYear: 1933,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'It Happened One Night',
  awardNumber: 7,
  releaseYear: 1934,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Mutiny on the Bounty',
  awardNumber: 8,
  releaseYear: 1935,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Great Ziegfeld',
  awardNumber: 9,
  releaseYear: 1936,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Life of Emile Zola',
  awardNumber: 10,
  releaseYear: 1937,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'You Can\'t Take It With You',
  awardNumber: 11,
  releaseYear: 1938,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Gone With The Wind',
  awardNumber: 12,
  releaseYear: 1939,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Rebecca',
  awardNumber: 13,
  releaseYear: 1940,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'How Green Was My Valley',
  awardNumber: 14,
  releaseYear: 1941,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Mrs. Miniver',
  awardNumber: 15,
  releaseYear: 1942,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Casablanca',
  awardNumber: 16,
  releaseYear: 1942,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Going My Way',
  awardNumber: 17,
  releaseYear: 1944,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Lost Weekend',
  awardNumber: 18,
  releaseYear: 1945,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Best Years of Our Lives',
  awardNumber: 19,
  releaseYear: 1946,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Gentlemen\'s Agreement',
  awardNumber: 20,
  releaseYear: 1947,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Hamlet',
  awardNumber: 21,
  releaseYear: 1948,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'All the King\'s Men',
  awardNumber: 22,
  releaseYear: 1949,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'All About Eve',
  awardNumber: 23,
  releaseYear: 1950,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'An American in Paris',
  awardNumber: 24,
  releaseYear: 1951,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Greatest Show on Earth',
  awardNumber: 25,
  releaseYear: 1952,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'From Here to Eternity',
  awardNumber: 26,
  releaseYear: 1953,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'On the Waterfront',
  awardNumber: 27,
  releaseYear: 1954,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Marty',
  awardNumber: 28,
  releaseYear: 1955,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Around the World in Eighty Days',
  awardNumber: 29,
  releaseYear: 1956,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Bridge on the River Kwai',
  awardNumber: 30,
  releaseYear: 1957,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Gigi',
  awardNumber: 31,
  releaseYear: 1958,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Ben-Hur',
  awardNumber: 32,
  releaseYear: 1959,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Apartment',
  awardNumber: 33,
  releaseYear: 1960,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'West Side Story',
  awardNumber: 34,
  releaseYear: 1961,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Lawrence of Arabia',
  awardNumber: 35,
  releaseYear: 1961,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Tom Jones',
  awardNumber: 36,
  releaseYear: 1963,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'My Fair Lady',
  awardNumber: 37,
  releaseYear: 1963,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Sound of Music',
  awardNumber: 38,
  releaseYear: 1965,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'A Man for All Seasons',
  awardNumber: 39,
  releaseYear: 1966,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'In the Heat of the Night',
  awardNumber: 40,
  releaseYear: 1967,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Oliver!',
  awardNumber: 41,
  releaseYear: 1968,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Midnight Cowboy',
  awardNumber: 42,
  releaseYear: 1969,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Patton',
  awardNumber: 43,
  releaseYear: 1970,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The French Connection',
  awardNumber: 44,
  releaseYear: 1971,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Godfather',
  awardNumber: 45,
  releaseYear: 1972,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Sting',
  awardNumber: 46,
  releaseYear: 1973,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Godfather: Part II',
  awardNumber: 47,
  releaseYear: 1974,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'One Flew Over the Cuckoo\'s Nest',
  awardNumber: 48,
  releaseYear: 1975,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Rocky',
  awardNumber: 49,
  releaseYear: 1976,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Annie Hall',
  awardNumber: 50,
  releaseYear: 1977,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Deer Hunter',
  awardNumber: 51,
  releaseYear: 1978,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Kramer vs. Kramer',
  awardNumber: 52,
  releaseYear: 1979,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Ordinary People',
  awardNumber: 53,
  releaseYear: 1980,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Chariots of Fire',
  awardNumber: 54,
  releaseYear: 1981,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Gandhi',
  awardNumber: 55,
  releaseYear: 1982,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Terms of Endearment',
  awardNumber: 56,
  releaseYear: 1983,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Amadeus',
  awardNumber: 57,
  releaseYear: 1984,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Out of Africa',
  awardNumber: 58,
  releaseYear: 1985,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Platoon',
  awardNumber: 59,
  releaseYear: 1986,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Last Emperor',
  awardNumber: 60,
  releaseYear: 1987,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Rain Man',
  awardNumber: 61,
  releaseYear: 1988,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Driving Miss Daisy',
  awardNumber: 62,
  releaseYear: 1988,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Dances with Wolves',
  awardNumber: 63,
  releaseYear: 1990,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Silence of the Lambs',
  awardNumber: 64,
  releaseYear: 1991,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Unforgiven',
  awardNumber: 65,
  releaseYear: 1992,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Schindler\'s List',
  awardNumber: 66,
  releaseYear: 1993,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Forest Gump',
  awardNumber: 67,
  releaseYear: 1994,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Braveheart',
  awardNumber: 68,
  releaseYear: 1995,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The English Patient',
  awardNumber: 69,
  releaseYear: 1996,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Titanic',
  awardNumber: 70,
  releaseYear: 1997,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Shakespeare in Love',
  awardNumber: 71,
  releaseYear: 1998,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'American Beauty',
  awardNumber: 72,
  releaseYear: 1999,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Gladiator',
  awardNumber: 73,
  releaseYear: 2000,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'A Beautiful Mind',
  awardNumber: 74,
  releaseYear: 2001,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Chicago',
  awardNumber: 75,
  releaseYear: 2002,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Lord of the Rings: The Return of the King',
  awardNumber: 76,
  releaseYear: 2003,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Million Dollar Baby',
  awardNumber: 77,
  releaseYear: 2004,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Crash',
  awardNumber: 78,
  releaseYear: 2004,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Departed',
  awardNumber: 79,
  releaseYear: 2006,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'No Country for Old Men',
  awardNumber: 80,
  releaseYear: 2007,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Slumdog Millionaire',
  awardNumber: 81,
  releaseYear: 2008,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Hurtlocker',
  awardNumber: 82,
  releaseYear: 2008,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The King\'s Speech',
  awardNumber: 83,
  releaseYear: 2010,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Artist',
  awardNumber: 84,
  releaseYear: 2011,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Argo',
  awardNumber: 85,
  releaseYear: 2012,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: '12 Years a Slave',
  awardNumber: 86,
  releaseYear: 2013,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Birdman, or The Unexpected Virtue of Ignorance',
  awardNumber: 87,
  releaseYear: 2014,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Spotlight',
  awardNumber: 88,
  releaseYear: 2015,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'Moonlight',
  awardNumber: 89,
  releaseYear: 2016,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT },
{ name: 'The Shape of Water',
  awardNumber: 90,
  releaseYear: 2017,
  seen: false,
  rating: null,
  review: null,
  synopsis:
   FILLER_TEXT } ]